# Generated by Django 3.2.16 on 2022-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_persons',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_for',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
